name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/**'
      - 'src/**'
      - 'build.gradle'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: repository 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application.yml 생성
        run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: gradlew 빌드 실행
        run: ./gradlew build

      - name: JaCoCo 리포트 추가
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 100
          min-coverage-changed-files: 100
          title: ✅ JaCoCo Code Coverage Report
          update-comment: true